-- ldoc configuration file
-- see https://raw.githubusercontent.com/lunarmodules/Penlight/master/lua/pl/app.lua
title = "Lua Api: Factorio Bot"
project = 'Factorio Bot'
description = 'Documentation for available Globals in LUA Scripting Interface'
full_description = [[
[![User Guide](https://img.shields.io/badge/user-guide-green)](https://arturh85.github.io/factorio-bot/userguide/)
[![MIT License](https://img.shields.io/github/license/arturh85/factorio-bot)](https://github.com/arturh85/factorio-bot/blob/master/LICENSE.txt)
[![GitHub issues](https://img.shields.io/github/issues/arturh85/factorio-bot)](https://github.com/arturh85/factorio-bot/issues)
[![codecov](https://codecov.io/gh/arturh85/factorio-bot/branch/master/graph/badge.svg?token=Q4I23JAT9A)](https://codecov.io/gh/arturh85/factorio-bot)
[![actions](https://github.com/arturh85/factorio-bot/actions/workflows/test.yml/badge.svg)](https://github.com/arturh85/factorio-bot/actions)
[![Dev Guide](https://img.shields.io/badge/dev-guide-red)](https://arturh85.github.io/factorio-bot/devguide/)
[![Github Repo](https://img.shields.io/badge/repo-github-blueviolet)](https://github.com/arturh85/factorio-bot)

The following documented items are automatically globally available when user lua scripts are run.
]]
file = {'src'}
no_summary = false
no_return_or_parms = false
format = 'markdown'
style = true
sort = true
