codecov:
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        # remove codecov minimum coverage requirements
        target: 0%
        # Allow the coverage to drop by X%, and posting a success status.
        threshold: 100%