[workspace]
members = [
    "app/src-tauri",
    "crates/*"
]
resolver = "2"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s" # "s": optimize for binary size
