name: 'LDOC'
description: 'Generate Lua Api Docs'
inputs:
  config-path:
    description: 'path to config.ld file'
    required: true
  source-path:
    description: 'path to lua source directory'
    required: true
  output-path:
    description: 'path to html output directory'
    required: true
runs:
  using: 'docker'
  image: 'docker://anibali/ldoc:latest'
  args:
    - '-o'
    - ${{ inputs.output-path }}c
    - '-c'
    - ${{ inputs.config-path }}
    - ${{ inputs.source-path }}