name: 'LDOC'
description: 'Generate Lua Api Docs'
inputs:
  config-path:
    description: 'path to config.ld file'
    required: true
  source-path:
    description: 'path to lua source files'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '-c'
    - ${{ inputs.config-path }}
    - ${{ inputs.source-path }}