//! A search that ranks candidate layouts by the flow they would sustain.
//!
//! # What this optimises, and what it does not
//!
//! The owner's question was *"we have so many goals and decisions ... maybe
//! genetic algorithms or some other stuff could optimize the plan at the end
//! ... or we make simulations, trying which layout / prio maximizes achieved
//! flow rate"*. The objective behind it is a base that **compounds** -- every
//! science pack automated, the base upgraded continuously -- not a completion
//! time. The quantity that compounds is a production *rate*, so that is what
//! the fitness here is: items per minute a layout would sustain, as
//! [`FlowGraph::sustained_production_rates`] predicts it, beside what the
//! layout costs in plates to stand up, so a rate can be read per plate
//! invested.
//!
//! **The search space is deliberately small and deliberately real.** A
//! candidate is a [`Layout`]: either a decoded blueprint fixture or a block
//! generated by [`ore_to_plate`] in the exact geometry of the fixture
//! `OreToPlateThree` from `scripts/rcontest.lua`, which has a live
//! measurement (36.2 plates/min, `docs/superpowers/notes/
//! 2026-09-07-the-block-was-drill-limited.md`). Generating in the measured
//! geometry is what makes the model's number checkable: `gen-3x2` **is** that
//! fixture, entity for entity (`generated_three_by_two_is_the_measured_fixture`
//! asserts it), so its predicted rate has a game number to stand beside.
//!
//! # Why enumeration and not a genetic algorithm
//!
//! One candidate costs a fresh [`EntityGraph`] holding the ore patch plus the
//! block, one `connect`, and one whole-base balance -- **milliseconds**, as
//! the `search` CLI measures and prints beside every row. The parametric
//! family is `drills x furnaces` and a whole 8x8 sweep is 64 evaluations,
//! under a second. A population-based search over a space this size would be
//! ranking noise against exhaustive truth; the owner's suggestion is kept in
//! mind for the day the space is combinatorial (siting, orientation, belt
//! topology), and is not warranted by the cost measured today.
//!
//! # What the ranking cannot see, stated up front
//!
//! Every limit of the flow graph is a limit here, and three of them decide
//! whether a ranking can be *trusted* rather than merely produced:
//!
//! - **A block nothing mines into reads as zero, not as slow.** The walk in
//!   [`FlowGraph::update`] roots only at a drill standing on ore or an
//!   offshore pump. A chest-fed or hand-fed smelter -- `TJunctionSmelter`,
//!   `FurnaceLine`, `SmeltRow24` -- has no incoming edge and scores 0. That
//!   is not a prediction the game will make, so those fixtures are reported
//!   with `reached = false` and excluded from the ranking rather than sorted
//!   to the bottom as if they were bad.
//! - **Fuel is invisible.** A burner's coal is not a recipe ingredient
//!   (`the_ground_is_not_a_recipe`), so a block whose coal branch is deleted
//!   scores identically to the same block with it. In the game the burner
//!   inserters stop when their hand charge burns out and the block makes
//!   nothing. [`ore_to_plate`] takes `coal: false` to build exactly that
//!   control; the CLI prints it beside its twin so the tie is visible.
//! - **A multi-output machine is scored per product**, one
//!   `ProductionLine` each with an independent outlet cap. The game stops
//!   the whole machine when any one output backs up. A layout that leaves
//!   one refinery product undrained is therefore scored at nameplate on the
//!   others when the true steady state is zero -- a search over oil layouts
//!   would exploit this immediately, and this module refuses to run one:
//!   [`Layout::multi_output_machines`] names the machines and the CLI marks
//!   the row `unscoreable` rather than ranking it.
//!
//! What the model *does* see is the constraint the measured fixtures were
//! built to probe: whether the drills or the furnaces bind. The 2x2 block
//! measured 28.7/min against 30.0 of drill supply, the 3x2 block 36.2 against
//! 37.5 of furnace capacity, and the balance reproduces both constraints
//! from prototypes. The `search` CLI prints `model / measured` for every
//! candidate handed a live number, which is how the bias is quantified rather
//! than assumed.

use crate::PlannerError;
use factorio_bot_core::blueprint::{self, Blueprint, BlueprintEntity, UndergroundHalf};
use factorio_bot_core::dashmap::DashMap;
use factorio_bot_core::factorio::util::add_to_rect;
use factorio_bot_core::graph::entity_graph::EntityGraph;
use factorio_bot_core::graph::flow_graph::FlowGraph;
use factorio_bot_core::num_traits::FromPrimitive;
use factorio_bot_core::types::{
    Direction, EntityType, FactorioEntity, FactorioEntityPrototype, FactorioRecipe, Pos, Position,
};
use std::collections::{BTreeMap, BTreeSet};
use std::sync::Arc;

/// Items this module treats as raw when pricing a layout: the plates a
/// smelter makes and the things a bot digs out of the ground. Everything
/// above these is expanded through its recipe; nothing below is charged.
const RAW_ITEMS: &[&str] = &["iron-plate", "copper-plate", "stone", "coal", "wood"];

/// The layouts of the two arms an `OreToPlate*` fixture is built from, as
/// constants rather than prose, so a change to the generator is a change to
/// a number a test compares against the decoded fixture.
mod geometry {
    /// Where the first furnace's row sits below the corner belt.
    pub const FIRST_FURNACE_Y: f64 = 8.0;
    /// Rows between furnaces.
    pub const FURNACE_PITCH: f64 = 3.0;
    /// How far the vertical belt runs past the last furnace's inserter.
    pub const BELT_TAIL: f64 = 1.5;
}

/// One candidate: a named list of blueprint entities at relative offsets.
#[derive(Debug, Clone)]
pub struct Layout {
    pub name: String,
    pub entities: Vec<BlueprintEntity>,
    /// Where the layout came from, for the report: a fixture name or the
    /// generator's parameters.
    pub note: String,
}

impl Layout {
    /// A layout decoded from blueprint text.
    pub fn from_blueprint(name: &str, text: &str) -> Result<Layout, PlannerError> {
        let bp: Blueprint =
            blueprint::decode(text).map_err(|err| PlannerError::BlueprintRefused {
                reason: format!("{err:?}"),
            })?;
        let note = format!("fixture, {} entities", bp.entities.len());
        Ok(Layout {
            name: name.to_owned(),
            entities: bp.entities,
            note,
        })
    }

    /// The blueprint string that places exactly these entities.
    pub fn blueprint_text(&self) -> String {
        blueprint::encode(&self.entities)
    }

    /// How many entities of each name the layout places.
    pub fn bill(&self) -> BTreeMap<String, u32> {
        let mut bill = BTreeMap::new();
        for e in &self.entities {
            *bill.entry(e.name.clone()).or_insert(0) += 1;
        }
        bill
    }

    /// Every machine in this layout that **can** run a multi-product recipe,
    /// with the recipes that make it so, given the prototype and recipe
    /// tables.
    ///
    /// A layout's entities carry no recipe (the blueprint allowlist refuses
    /// the key), so the question the tables can answer is narrower than
    /// "what will this machine make": it is whether any recipe in any
    /// crafting category the machine accepts yields more than one product.
    /// Under Space Age `oil-processing` holds `basic-oil-processing` (one
    /// product) beside `advanced-oil-processing` (three), so a rule of
    /// "every recipe is multi-output" never fires on a refinery -- the first
    /// version of this said exactly that, and was checked against the dump
    /// before it shipped. The conservative rule is the honest one: until the
    /// recipe is known, a machine that *could* be scored per product is
    /// unscoreable, and the caller says so by name rather than ranking it.
    ///
    /// Derived from the tables, not from a list of names, so a modded
    /// machine of the same shape is caught too.
    pub fn multi_output_machines(
        &self,
        prototypes: &DashMap<String, FactorioEntityPrototype>,
        recipes: &DashMap<String, FactorioRecipe>,
    ) -> Vec<MultiOutputMachine> {
        let mut out: Vec<MultiOutputMachine> = vec![];
        for e in &self.entities {
            if out.iter().any(|m| m.machine == e.name) {
                continue;
            }
            let Some(proto) = prototypes.get(&e.name) else {
                continue;
            };
            let Some(categories) = proto.crafting_categories.as_ref() else {
                continue;
            };
            let mut multi: Vec<String> = recipes
                .iter()
                .filter(|r| categories.contains(&r.category) && r.products.len() > 1)
                .map(|r| r.key().clone())
                .collect();
            if multi.is_empty() {
                continue;
            }
            multi.sort();
            out.push(MultiOutputMachine {
                machine: e.name.clone(),
                recipes: multi,
            });
        }
        out.sort_by(|a, b| a.machine.cmp(&b.machine));
        out
    }
}

/// A machine a per-product balance cannot score honestly, and why.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MultiOutputMachine {
    pub machine: String,
    /// The multi-product recipes it accepts, sorted by name.
    pub recipes: Vec<String>,
}

impl std::fmt::Display for MultiOutputMachine {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{} (can run {})", self.machine, self.recipes.join(", "))
    }
}

fn bp(name: &str, x: f64, y: f64, direction: u8) -> BlueprintEntity {
    BlueprintEntity {
        name: name.to_owned(),
        offset: Position::new(x, y),
        direction,
        underground_half: None,
    }
}

/// `drills` burner drills feeding `furnaces` stone furnaces, in the geometry
/// of the measured `OreToPlateThree` fixture.
///
/// Drills stand in a row at `(2k, -1)` facing south and drop onto an
/// east-running belt at `y = 0.5`; the belt turns south at `x = 2D + 0.5`
/// and runs past a column of furnaces, each fed by a burner inserter picking
/// from the belt. Coal enters by a T-junction from the east -- a chest, a
/// burner inserter and three westbound belt tiles -- so it lands on the
/// belt's north lane while the ore, dropped from the north, lands on the
/// south lane (the two lane rules under "Known Issues" in `CLAUDE.md`).
///
/// `coal = false` omits the coal branch. **That is a control, not a
/// design**: the game stops such a block once its burner arms' hand charge
/// is spent, and the flow model cannot tell the two apart.
pub fn ore_to_plate(drills: u32, furnaces: u32, coal: bool) -> Layout {
    ore_to_plate_with(drills, furnaces, coal, true)
}

/// [`ore_to_plate`] with the output side optional.
///
/// `drained = true` adds, per furnace, a burner inserter on the far side
/// picking from the furnace into an iron chest. **That is the measuring
/// apparatus of `scripts/rate_three_drills.lua` made into entities**, not a
/// design: the measured fixtures have no output side, their furnaces were
/// emptied by script so the number would be a rate rather than a storage
/// count, and a burner arm carrying only plates has no fuel source and stops
/// in the game. It is here because the flow walk records a furnace's output
/// only on an edge *leaving* it -- `drained = false` reproduces the fixture
/// exactly and scores **zero plates**, which is the game's own long-run
/// answer for a block whose result slots fill (200 plates, then nothing),
/// reached by the model for a different reason.
pub fn ore_to_plate_with(drills: u32, furnaces: u32, coal: bool, drained: bool) -> Layout {
    let d = f64::from(drills);
    let corner_x = 2.0 * d + 0.5;
    let mut entities = vec![];
    for k in 0..drills {
        entities.push(bp("burner-mining-drill", 2.0 * f64::from(k), -1.0, 8));
    }
    for i in 0..(2 * drills) {
        entities.push(bp("transport-belt", f64::from(i) + 0.5, 0.5, 4));
    }
    entities.push(bp("transport-belt", corner_x, 0.5, 8));
    if coal {
        for i in 1..=3 {
            entities.push(bp("transport-belt", corner_x + f64::from(i), 0.5, 12));
        }
        entities.push(bp("burner-inserter", corner_x + 4.0, 0.5, 4));
        entities.push(bp("iron-chest", corner_x + 5.0, 0.5, 0));
    }
    let last_furnace_y =
        geometry::FIRST_FURNACE_Y + geometry::FURNACE_PITCH * f64::from(furnaces.saturating_sub(1));
    let belt_end_y = last_furnace_y + geometry::BELT_TAIL;
    let mut y = 1.5;
    while y <= belt_end_y {
        entities.push(bp("transport-belt", corner_x, y, 8));
        y += 1.0;
    }
    for j in 0..furnaces {
        let fy = geometry::FIRST_FURNACE_Y + geometry::FURNACE_PITCH * f64::from(j);
        entities.push(bp("stone-furnace", corner_x + 2.5, fy, 0));
        entities.push(bp("burner-inserter", corner_x + 1.0, fy + 0.5, 12));
        if drained {
            entities.push(bp("burner-inserter", corner_x + 4.0, fy + 0.5, 12));
            entities.push(bp("iron-chest", corner_x + 5.0, fy + 0.5, 0));
        }
    }
    Layout {
        name: format!(
            "gen-{drills}x{furnaces}{}{}",
            if coal { "" } else { "-nocoal" },
            if drained { "" } else { "-undrained" }
        ),
        entities,
        note: format!(
            "generated: {drills} burner drill(s), {furnaces} stone furnace(s){}{}",
            if coal { "" } else { ", NO coal branch" },
            if drained { "" } else { ", NO output side" }
        ),
    }
}

/// The ore the search stands its candidates on: one patch's tiles.
#[derive(Debug, Clone)]
pub struct OrePatch {
    pub resource: String,
    /// Tile floors, the same key `EntityGraph::resources` uses.
    pub tiles: BTreeSet<Pos>,
}

impl OrePatch {
    /// The patch of `resource` nearest the origin in `graph`, by its nearest
    /// tile.
    pub fn nearest(graph: &EntityGraph, resource: &str) -> Option<OrePatch> {
        let patches = graph.resource_patches(resource);
        let mut best: Option<(f64, OrePatch)> = None;
        for patch in patches {
            let tiles: BTreeSet<Pos> = patch.elements.iter().map(Pos::from).collect();
            let nearest = patch
                .elements
                .iter()
                .map(|p| p.x() * p.x() + p.y() * p.y())
                .fold(f64::INFINITY, f64::min);
            let candidate = OrePatch {
                resource: resource.to_owned(),
                tiles,
            };
            match &best {
                Some((d, _)) if d.total_cmp(&nearest).is_le() => {}
                _ => best = Some((nearest, candidate)),
            }
        }
        best.map(|(_, p)| p)
    }

    /// The tiles as resource entities, at tile centres -- the half-tile
    /// offset `EntityGraph` floors away and the mod never omits.
    pub fn entities(&self) -> Vec<FactorioEntity> {
        self.tiles
            .iter()
            .map(|Pos(x, y)| {
                FactorioEntity::new_resource(
                    &Position::new(f64::from(*x) + 0.5, f64::from(*y) + 0.5),
                    Direction::North,
                    &self.resource,
                )
            })
            .collect()
    }
}

/// Where a layout's drills land, and how much of the patch is under them.
#[derive(Debug, Clone, PartialEq)]
pub struct Siting {
    pub anchor: Position,
    /// Ore tiles under drill footprints.
    pub covered: usize,
    /// Drill footprint tiles in total.
    pub possible: usize,
}

/// The tiles a `width`-by-`width` drill centred at `centre` covers.
///
/// A 2x2 sits on a tile boundary (integer centre) and a 3x3 on a tile
/// centre (half-integer); flooring `centre - width/2` handles both.
fn drill_tiles(centre: &Position, width: i32) -> Vec<Pos> {
    let half = f64::from(width) / 2.;
    let x0 = (centre.x() - half + 1e-9).floor() as i32;
    let y0 = (centre.y() - half + 1e-9).floor() as i32;
    let mut tiles = Vec::with_capacity((width * width) as usize);
    for dy in 0..width {
        for dx in 0..width {
            tiles.push(Pos(x0 + dx, y0 + dy));
        }
    }
    tiles
}

/// The integer anchor putting the most of the layout's drills on ore,
/// nearest the origin among ties. `None` when the layout has no drill.
///
/// Integer anchors only: a burner drill is 2x2 and sits on a tile *boundary*
/// (`method::util::tile_alignment`), so an anchor of the wrong parity is
/// not a worse site but one the game will not honour.
pub fn site(
    layout: &Layout,
    ore: &OrePatch,
    prototypes: &DashMap<String, FactorioEntityPrototype>,
) -> Option<Siting> {
    // A drill is whatever the prototype table calls a mining drill, with the
    // tile footprint its collision box spans: 2x2 for a burner drill, 3x3
    // for an electric one. Matching on one name here mis-filed `MinerLine`
    // (13 electric drills) as "no drill in the layout" on the first run.
    let drills: Vec<(&BlueprintEntity, i32)> = layout
        .entities
        .iter()
        .filter_map(|e| {
            let proto = prototypes.get(&e.name)?;
            if proto.entity_type != EntityType::MiningDrill.to_string() {
                return None;
            }
            // `ceil`, not `round`: a collision box is shrunk inside its tiles
            // (a burner drill's is 1.398 wide for a 2x2), and rounding it
            // filed every drill as one tile on the first run.
            let width = (proto.collision_box.width()).ceil().max(1.) as i32;
            Some((e, width))
        })
        .collect();
    if drills.is_empty() {
        return None;
    }
    let (min_x, max_x, min_y, max_y) = ore.tiles.iter().fold(
        (i32::MAX, i32::MIN, i32::MAX, i32::MIN),
        |(a, b, c, d), Pos(x, y)| (a.min(*x), b.max(*x), c.min(*y), d.max(*y)),
    );
    let possible: usize = drills
        .iter()
        .map(|(_, w)| (*w as usize) * (*w as usize))
        .sum();
    let mut best: Option<(usize, f64, Position)> = None;
    for ay in (min_y - 4)..=(max_y + 4) {
        for ax in (min_x - 4)..=(max_x + 4) {
            let anchor = Position::new(f64::from(ax), f64::from(ay));
            let covered: usize = drills
                .iter()
                .map(|(d, width)| {
                    let centre = anchor.add(&d.offset);
                    drill_tiles(&centre, *width)
                        .iter()
                        .filter(|t| ore.tiles.contains(t))
                        .count()
                })
                .sum();
            if covered == 0 {
                continue;
            }
            let dist = anchor.x() * anchor.x() + anchor.y() * anchor.y();
            let better = match &best {
                None => true,
                Some((c, d, _)) => covered > *c || (covered == *c && dist < *d),
            };
            if better {
                best = Some((covered, dist, anchor));
            }
        }
    }
    best.map(|(covered, _, anchor)| Siting {
        anchor,
        covered,
        possible,
    })
}

/// A layout's entities as the world would hold them, at `anchor`.
///
/// Built through `FactorioEntity`'s own constructors wherever one exists,
/// because those are what carry the `drop_position` and `pickup_position`
/// [`EntityGraph::connect`] wires a drill and an inserter by. A name with no
/// constructor gets its footprint from the prototype table and its type from
/// the same, and connects only as far as the belt and pipe rules reach.
pub fn entities_at(
    layout: &Layout,
    anchor: &Position,
    prototypes: &DashMap<String, FactorioEntityPrototype>,
) -> Vec<FactorioEntity> {
    layout
        .entities
        .iter()
        .map(|e| {
            let position = anchor.add(&e.offset);
            let direction = Direction::from_u8(e.direction).unwrap_or(Direction::North);
            match e.name.as_str() {
                "transport-belt" => FactorioEntity::new_transport_belt(&position, direction),
                "burner-mining-drill" => {
                    FactorioEntity::new_burner_mining_drill(&position, direction)
                }
                "electric-mining-drill" => {
                    FactorioEntity::new_electric_mining_drill(&position, direction)
                }
                "stone-furnace" => FactorioEntity::new_stone_furnace(&position, direction),
                "splitter" => FactorioEntity::new_splitter(&position, direction),
                "underground-belt" => FactorioEntity::new_underground_belt(
                    &position,
                    direction,
                    e.underground_half.unwrap_or(UndergroundHalf::Input),
                ),
                name if name.ends_with("inserter") => {
                    FactorioEntity::new_named_inserter(name.to_owned(), &position, direction)
                }
                name => {
                    let proto = prototypes.get(name);
                    let entity_type = proto
                        .as_ref()
                        .map(|p| p.entity_type.clone())
                        .unwrap_or_else(|| EntityType::Container.to_string());
                    let bounding_box = proto
                        .as_ref()
                        .map(|p| add_to_rect(&p.collision_box, &position))
                        .unwrap_or_else(|| {
                            add_to_rect(
                                &factorio_bot_core::types::Rect::from_wh(0.8, 0.8),
                                &position,
                            )
                        });
                    FactorioEntity {
                        name: name.to_owned(),
                        entity_type,
                        position: position.clone(),
                        bounding_box,
                        direction: e.direction,
                        ..Default::default()
                    }
                }
            }
        })
        .collect()
}

/// What the model says one sited layout would do.
#[derive(Debug, Clone, PartialEq)]
pub struct Fitness {
    pub name: String,
    pub siting: Siting,
    /// Items per minute the whole-base balance sustains, per item.
    pub sustained_per_min: BTreeMap<String, f64>,
    /// Items per minute at nameplate, ingredients assumed.
    pub nameplate_per_min: BTreeMap<String, f64>,
    /// Whether the flow walk reached any producer at all. `false` means the
    /// zero above is "the model knows of nothing arriving", not "nothing
    /// arrives" -- see the module doc.
    pub reached: bool,
    /// Entities placed.
    pub entities: usize,
    /// Raw items to build it, expanded through the recipe table.
    pub cost: BTreeMap<String, f64>,
}

impl Fitness {
    /// Plates per minute -- the rate this search ranks on.
    pub fn plates_per_min(&self) -> f64 {
        self.sustained_per_min
            .get("iron-plate")
            .copied()
            .unwrap_or_default()
    }

    /// Iron plates the layout costs to build.
    pub fn iron_cost(&self) -> f64 {
        self.cost.get("iron-plate").copied().unwrap_or_default()
    }

    /// Minutes until the block has made back the iron it cost. `None` when
    /// it makes nothing.
    pub fn payback_minutes(&self) -> Option<f64> {
        let rate = self.plates_per_min();
        (rate > 0.).then(|| self.iron_cost() / rate)
    }
}

/// Expands `item` through the recipe table down to [`RAW_ITEMS`].
///
/// The recipe named after the item wins; otherwise the first recipe (by
/// name) producing it. An item nothing makes is charged as itself, so a
/// name outside the table is visible in the bill rather than dropped.
fn raw_cost(
    item: &str,
    amount: f64,
    recipes: &DashMap<String, FactorioRecipe>,
    depth: usize,
    into: &mut BTreeMap<String, f64>,
) {
    if RAW_ITEMS.contains(&item) || depth > 12 {
        *into.entry(item.to_owned()).or_insert(0.) += amount;
        return;
    }
    let recipe_name = if recipes.contains_key(item) {
        Some(item.to_owned())
    } else {
        let mut names: Vec<String> = recipes
            .iter()
            .filter(|r| r.products.iter().any(|p| p.name == item))
            .map(|r| r.key().clone())
            .collect();
        names.sort();
        names.into_iter().next()
    };
    let Some(recipe_name) = recipe_name else {
        *into.entry(item.to_owned()).or_insert(0.) += amount;
        return;
    };
    let Some(recipe) = recipes.get(&recipe_name) else {
        *into.entry(item.to_owned()).or_insert(0.) += amount;
        return;
    };
    let yield_ = recipe
        .products
        .iter()
        .find(|p| p.name == item)
        .map(|p| f64::from(p.amount).max(1.))
        .unwrap_or(1.);
    let crafts = amount / yield_;
    for ingredient in recipe.ingredients.iter().flatten() {
        raw_cost(
            &ingredient.name,
            crafts * f64::from(ingredient.amount),
            recipes,
            depth + 1,
            into,
        );
    }
}

/// Scores one layout at one anchor on one patch: a fresh entity graph holding
/// the ore and the block, wired by this binary's rules, balanced by the flow
/// graph.
pub fn evaluate(
    layout: &Layout,
    siting: &Siting,
    ore: &OrePatch,
    prototypes: &Arc<DashMap<String, FactorioEntityPrototype>>,
    recipes: &Arc<DashMap<String, FactorioRecipe>>,
) -> Result<Fitness, PlannerError> {
    let graph = EntityGraph::new(prototypes.clone(), recipes.clone());
    let mut entities = ore.entities();
    let block = entities_at(layout, &siting.anchor, prototypes);
    let placed = block.len();
    entities.extend(block);
    graph
        .add(entities, None)
        .map_err(|err| PlannerError::BlueprintRefused {
            reason: format!("entity graph refused the block: {err}"),
        })?;
    graph
        .connect()
        .map_err(|err| PlannerError::BlueprintRefused {
            reason: format!("entity graph could not wire the block: {err}"),
        })?;
    let flow = FlowGraph::new(Arc::new(graph));
    let nameplate = flow.production_rates();
    let sustained = flow.sustained_production_rates();
    let reached = !nameplate.is_empty();
    let mut cost = BTreeMap::new();
    for (name, count) in layout.bill() {
        raw_cost(&name, f64::from(count), recipes, 0, &mut cost);
    }
    Ok(Fitness {
        name: layout.name.clone(),
        siting: siting.clone(),
        sustained_per_min: sustained.into_iter().map(|(k, v)| (k, v * 60.)).collect(),
        nameplate_per_min: nameplate.into_iter().map(|(k, v)| (k, v * 60.)).collect(),
        reached,
        entities: placed,
        cost,
    })
}

/// The scored candidates, best first by sustained plates per minute; a
/// candidate the walk never reached sorts after every one it did, whatever
/// its zero says.
pub fn rank(mut scored: Vec<Fitness>) -> Vec<Fitness> {
    // Rates are compared at a thousandth of a plate a minute: the balance is
    // a damped iteration converged to 1e-12, and two blocks that both make
    // exactly 75/min must tie on rate and fall through to cost rather than
    // be ordered by which one's noise landed higher.
    let rate = |f: &Fitness| (f.plates_per_min() * 1000.).round();
    scored.sort_by(|a, b| {
        b.reached
            .cmp(&a.reached)
            .then_with(|| rate(b).total_cmp(&rate(a)))
            .then_with(|| a.iron_cost().total_cmp(&b.iron_cost()))
            .then_with(|| a.name.cmp(&b.name))
    });
    scored
}

#[cfg(test)]
mod tests {
    use super::*;
    use factorio_bot_core::test_utils::{fixture_entity_prototypes, fixture_recipes};

    /// `OreToPlateThree` from `scripts/rcontest.lua`, verbatim: the block
    /// measured live at 36.2 plates/min.
    const ORE_TO_PLATE_THREE: &str = "0eNqd1t1ugjAUwPF36TUQDrR8vcR24d2yLKBnWxMoptRlxvDuq7pEIyU7Z5dS+dnQ/osn0fUH3FttnGhOQjscRHN3LRJ922Hvrz1Z3IzPfetw82kR/Qgap53GSTQvp+uH45s5DB1a0UAkTDugv8/Z1kz70brYO2dwP07+ttGcf+9bNEWiInEUTZqoORI7bXF7Ha3maMFmbBYobM5mMwor2WxOYRWblRS2YLOKwpZstqCwFZstKWzNZisKCynbrUkuvzMghQb/KI2UGvBbA1JsQK8N1o4cGXLpuWUsl95bznLpwUmWSy9OsVx6cvWaC1noXUFvruLB9OhKHnyLTtvRxNtPnELb937/hphbYt3BGrSxNhNa58eWVspZq0w+yoM22nzEO6v7PhDEhY6B8GJXPFnS5YL+NMq1Mz28XLfSJjcajN+9324xsHGvanCxKv70lidteH41b34AlwlyliFN0t+FSNKHpYgWf7LSO/2vcNa35dKF+TUSX2inyxdUkdWyrlUuM8j9c5l/AEupkxI=";

    fn key(e: &BlueprintEntity) -> (String, i64, i64, u8) {
        (
            e.name.clone(),
            (e.offset.x() * 2.).round() as i64,
            (e.offset.y() * 2.).round() as i64,
            e.direction,
        )
    }

    /// The generator's whole reason to exist: `gen-3x2` is the measured
    /// fixture, entity for entity, so its predicted rate has a game number
    /// to stand beside.
    #[test]
    fn generated_three_by_two_is_the_measured_fixture() {
        let fixture = Layout::from_blueprint("OreToPlateThree", ORE_TO_PLATE_THREE).unwrap();
        let generated = ore_to_plate_with(3, 2, true, false);
        let mut a: Vec<_> = fixture.entities.iter().map(key).collect();
        let mut b: Vec<_> = generated.entities.iter().map(key).collect();
        a.sort();
        b.sort();
        assert_eq!(a.len(), 31);
        assert_eq!(a, b);
    }

    /// `encode` is the inverse of `decode`: the fixture survives a round trip
    /// through the text form the game and `Goal::Built` read.
    #[test]
    fn a_layout_survives_the_blueprint_round_trip() {
        let fixture = Layout::from_blueprint("OreToPlateThree", ORE_TO_PLATE_THREE).unwrap();
        let text = fixture.blueprint_text();
        let back = Layout::from_blueprint("again", &text).unwrap();
        let mut a: Vec<_> = fixture.entities.iter().map(key).collect();
        let mut b: Vec<_> = back.entities.iter().map(key).collect();
        a.sort();
        b.sort();
        assert_eq!(a, b);
    }

    fn square_patch(name: &str, half: i32) -> OrePatch {
        let mut tiles = BTreeSet::new();
        for y in -half..half {
            for x in -half..half {
                tiles.insert(Pos(x, y));
            }
        }
        OrePatch {
            resource: name.to_owned(),
            tiles,
        }
    }

    fn scored(layout: &Layout) -> Fitness {
        let prototypes = Arc::new(fixture_entity_prototypes());
        let recipes = Arc::new(fixture_recipes());
        let ore = square_patch("iron-ore", 12);
        let siting = site(layout, &ore, &prototypes).expect("a block with drills can be sited");
        assert_eq!(
            siting.covered, siting.possible,
            "every drill of {} stands wholly on ore",
            layout.name
        );
        evaluate(layout, &siting, &ore, &prototypes, &recipes).expect("evaluates")
    }

    /// The constraint the live measurements found, reproduced from
    /// prototypes: two drills bind at 30 ore/min, three drills push the
    /// constraint onto two furnaces at 37.5 plates/min.
    #[test]
    fn the_balance_finds_the_binding_constraint_the_game_found() {
        let two = scored(&ore_to_plate(2, 2, true));
        let three = scored(&ore_to_plate(3, 2, true));
        assert!(two.reached && three.reached);
        assert!(
            (two.plates_per_min() - 30.0).abs() < 1e-6,
            "2x2 is drill-limited at 30/min, got {}",
            two.plates_per_min()
        );
        assert!(
            (three.plates_per_min() - 37.5).abs() < 1e-6,
            "3x2 is furnace-limited at 37.5/min, got {}",
            three.plates_per_min()
        );
    }

    /// The differential-bias control: the model cannot see fuel, so the
    /// block with no coal branch scores exactly the same. Asserted as a fact
    /// about the model, not a wish.
    #[test]
    fn the_model_cannot_tell_a_block_from_its_unfuelled_twin() {
        let fuelled = scored(&ore_to_plate(3, 2, true));
        let unfuelled = scored(&ore_to_plate(3, 2, false));
        assert_eq!(fuelled.sustained_per_min, unfuelled.sustained_per_min);
        assert!(fuelled.plates_per_min() > 0.);
    }

    /// A block sited off the ore reads as zero and `reached = false`.
    #[test]
    fn a_block_off_the_ore_is_unreached_not_slow() {
        let prototypes = Arc::new(fixture_entity_prototypes());
        let recipes = Arc::new(fixture_recipes());
        let ore = square_patch("iron-ore", 3);
        let layout = ore_to_plate(2, 2, true);
        let off = Siting {
            anchor: Position::new(200., 200.),
            covered: 0,
            possible: 8,
        };
        let fit = evaluate(&layout, &off, &ore, &prototypes, &recipes).unwrap();
        assert!(!fit.reached);
        assert_eq!(fit.plates_per_min(), 0.);
    }

    /// The multi-output guard fires on a machine whose category holds ANY
    /// multi-product recipe, and names the recipe; a furnace whose only
    /// recipe has one product is left alone.
    #[test]
    fn a_machine_that_could_run_a_multi_product_recipe_is_named() {
        let prototypes = fixture_entity_prototypes();
        let recipes = fixture_recipes();
        // The fixture tables predate Space Age's oil recipes, so the shape is
        // built here from a recipe the tables do have.
        let mut refinery = prototypes
            .get("oil-refinery")
            .expect("fixture has a refinery")
            .clone();
        refinery.crafting_categories = Some(vec!["oil-processing".to_owned()]);
        prototypes.insert("oil-refinery".to_owned(), refinery);
        let mut single = recipes
            .get("iron-plate")
            .expect("fixture has iron-plate")
            .clone();
        single.name = "basic-oil-processing".to_owned();
        single.category = "oil-processing".to_owned();
        let mut multi = single.clone();
        multi.name = "advanced-oil-processing".to_owned();
        multi.products.push(multi.products[0].clone());
        recipes.insert(single.name.clone(), single);
        recipes.insert(multi.name.clone(), multi);

        let layout = Layout {
            name: "oil".into(),
            entities: vec![
                bp("oil-refinery", 2.5, 2.5, 0),
                bp("stone-furnace", 9., 9., 0),
            ],
            note: String::new(),
        };
        let flagged = layout.multi_output_machines(&prototypes, &recipes);
        assert_eq!(
            flagged,
            vec![MultiOutputMachine {
                machine: "oil-refinery".into(),
                recipes: vec!["advanced-oil-processing".into()],
            }]
        );
    }

    /// Both drill sizes land on the tiles the game would mine.
    #[test]
    fn drill_footprints_follow_the_box() {
        let two: BTreeSet<Pos> = drill_tiles(&Position::new(0., -1.), 2)
            .into_iter()
            .collect();
        assert_eq!(
            two,
            [Pos(-1, -2), Pos(0, -2), Pos(-1, -1), Pos(0, -1)]
                .into_iter()
                .collect()
        );
        let three: BTreeSet<Pos> = drill_tiles(&Position::new(1.5, 0.5), 3)
            .into_iter()
            .collect();
        assert_eq!(three.len(), 9);
        assert!(three.contains(&Pos(0, -1)) && three.contains(&Pos(2, 1)));
    }

    /// The cost is derived from the recipe table, not typed: a stone furnace
    /// is five stone, a burner drill is three gears, three plates and a
    /// furnace.
    #[test]
    fn cost_is_expanded_through_recipes() {
        let one = scored(&ore_to_plate(1, 1, false));
        // 1 drill (3 gear = 6 plate, +3 plate, + furnace 5 stone),
        // 1 furnace (5 stone), 1 burner inserter (1 plate + 1 gear = 3 plate),
        // belts: 2 + 1 + (3*1+6 = 9) = 12 belts -> 6 crafts of (1 plate + 1 gear) = 18 plate
        let stone = one.cost.get("stone").copied().unwrap_or_default();
        assert!((stone - 10.).abs() < 1e-9, "stone {stone}");
        // ... plus the output side: one more burner inserter (3) and an
        // iron chest (8).
        let iron = one.iron_cost();
        assert!(
            (iron - (9. + 3. + 18. + 3. + 8.)).abs() < 1e-9,
            "iron {iron}"
        );
    }

    /// Ranking puts reached candidates ahead of unreached ones and the
    /// higher rate first; ties break on the cheaper block.
    #[test]
    fn rank_prefers_reached_then_rate_then_cost() {
        let a = scored(&ore_to_plate(1, 2, true));
        let b = scored(&ore_to_plate(3, 2, true));
        let c = scored(&ore_to_plate(3, 3, true));
        let order: Vec<String> = rank(vec![a, c.clone(), b.clone()])
            .into_iter()
            .map(|f| f.name)
            .collect();
        // 3x2 and 3x3 both make 45 ore/min into >= 37.5 of furnace: 3x3 makes
        // 45, 3x2 makes 37.5, 1x2 makes 15.
        assert_eq!(order, vec!["gen-3x3", "gen-3x2", "gen-1x2"]);
        assert!(c.plates_per_min() > b.plates_per_min());
    }
}
