[package]
name = "factorio-bot"
version = "0.1.0"
description = "factorio-bot"
authors = [ "Artur Hallmann <arturh@arturh.de>" ]
license = "MIT"
repository = ""
default-run = "factorio-bot"
edition = "2018"
build = "src/build.rs"

[dependencies]
serde_json = "1.0"
factorio-bot-backend = { path = "../../backend/" }
serde = { version = "1.0", features = [ "derive" ] }
tauri = { version = "0.11", features = [ "all-api" ] }

[target."cfg(windows)".build-dependencies]
winres = "0.1"

[features]
embedded-server = [ "tauri/embedded-server" ]
no-server = [ "tauri/no-server" ]

[[bin]]
name = "factorio-bot"
path = "src/main.rs"
