-- Was it lazy chunk generation, a writeout gap, or a wandering unit?
--
-- I put "ungenerated ground reads as clear" into CLAUDE.md as the mechanism
-- behind four failed siting attempts. The other session challenged it with
-- measurements: `writeout_tiles` writes EVERY tile of a generated chunk, so a
-- tile in the model means the chunk was generated; `map.json` holds 409,600
-- tiles over a hard-edged [-320,320) square with no holes; and (44.5, 0.5) is
-- 44 tiles from spawn, well inside it. Their alternative is a known defect --
-- 54 of 419 chunks returned `{}` from `writeout_entities` -- which would leave
-- a chunk generated, its tiles present, and its ENTITIES missing.
--
-- My own evidence does not fit my story either. The run that finally succeeded
-- used the SAME seed and the SAME explicit anchor (40,0), and the game reported
-- `1 entities, none blocking` with the build completing clean. A tree generated
-- deterministically cannot be present in one run and absent in the next. So a
-- third candidate is in play: `Occupant::Terrain` reads "a tree, cliff, rock or
-- UNIT", and a unit walks.
--
-- THE DISCRIMINATOR IS ALREADY IN THE BINDINGS. `rcon.*` asks the GAME;
-- `world.*` asks the PLANNER'S MODEL. Asking both, before and after a walk,
-- separates every hypothesis:
--
--   game empty + model empty, both fill after the walk  -> lazy generation
--   game FULL  + model empty                            -> writeout gap
--   contents differ between two identical queries       -> something moved
--
-- Nothing is built. This run only looks.
print("start why the tree")

local BP = "0eNqdlE1ugzAQRu/iNUT+wYC5RpZVVUEyVS2BiYypGkW5e02iJq3iJDPdgQc/Hh6+ObCun2HnrQusOTAbYGDNr7WM9W0HfVxbt2H2bYDteoA+gI8lcMEGCxNrXg7nm/2bm4cuFhuRMdcOEDcG37ppN/qQR9BC3I1T3Da65YVf8cmVztieNXyljxnbWg+bc7U4ZjdYicZKClahsYqCLdDYgoLVaKymYEs0tqRgKzS2omBrNLamYA0aayhYwfF54CQwIWikpIlr1KwfXb75gOlBevN4cUxhrtHqZu/A59ZN4M8D5B7rRpCnyAVKUD4T1HhBSRMsUYLqmWCFF1Q0wZo8SE6Sf8B1CmzoYI4BS4460gtUpY9UCvyRXlgSc6RS4sk/406gwNccTWF0kL9HfLuBBPYEVcnvLvB2hmSnsXbmgV1JGBWCpFdh9ZZxetevpvcW+VsbWnNzmfJTnN5dnJ8StPbe8ZP/6C9SUBEbvBi+ZuwT/HSq6VKawhitCimUiMVvK5iiXA=="
local AX, AY = 40, 0
-- The tile the refusal named, and the disc that contains the whole block.
local PROBE = { x = 46, y = 0 }
local TILE  = { x = 44.5, y = 0.5 }

local function census(label)
  local g = rcon.find_entities_in_radius(PROBE, 12)
  local m = world.find_entities_in_radius(PROBE, 12)
  local gn = (type(g) == "table") and #g or -1
  local mn = (type(m) == "table") and #m or -1
  print(string.format("%-22s GAME=%-4s MODEL=%s", label, tostring(gn), tostring(mn)))
  local function names(t)
    if type(t) ~= "table" then return "(not a table)" end
    local seen = {}
    for _, e in ipairs(t) do seen[e.name or "?"] = (seen[e.name or "?"] or 0) + 1 end
    local parts = {}
    for n, c in pairs(seen) do parts[#parts+1] = n .. "x" .. c end
    table.sort(parts)
    return (#parts > 0) and table.concat(parts, ", ") or "(nothing)"
  end
  print("    game  sees: " .. names(g))
  print("    model sees: " .. names(m))
  -- Anything within 2 tiles of the tile the refusal actually named.
  for _, pair in ipairs({ { "game", g }, { "model", m } }) do
    if type(pair[2]) == "table" then
      for _, e in ipairs(pair[2]) do
        local dx = (e.position.x or 0) - TILE.x
        local dy = (e.position.y or 0) - TILE.y
        if (dx * dx + dy * dy) < 4 then
          print(string.format("    %s: %s at (%.2f,%.2f) -- within 2 tiles of the named tile",
            pair[1], e.name or "?", e.position.x, e.position.y))
        end
      end
    end
  end
end

-- Does the PLANNER refuse this exact anchor, and for what? This is the same
-- call the failing runs made, minus the build.
local function try_plan(label)
  local ok, err = pcall(function() return goal.plan(goal.built(BP, { x = AX, y = AY })) end)
  if ok then
    print(string.format("%-22s planner ACCEPTS the anchor", label))
  else
    print(string.format("%-22s planner REFUSES: %s", label, tostring(err):gsub("%s+", " "):sub(1, 150)))
  end
end

census("before any walk")
try_plan("before any walk")

local scout = (type(rcon.players()[1]) == "table")
  and rcon.players()[1].player_id or rcon.players()[1]
print("walking bot " .. tostring(scout) .. " to the probe point")
pcall(function() rcon.move(scout, PROBE, 6) end)

census("after the walk")
try_plan("after the walk")

print("")
print("If GAME was empty before and populated after, the chunk was generated by")
print("the walk and CLAUDE.md is right. If GAME was populated all along while")
print("MODEL was empty, it is the writeout gap and CLAUDE.md names the wrong")
print("mechanism. If the planner refused with nothing standing in either, the")
print("cause is neither and I have been wrong twice.")
print("end why the tree")
