//! A replan against the world `run-1788941729-70024` left standing, and the
//! two shapes of "a replan does not recognise its own half-built work".
//!
//! The run (seed 31337, four headless bots at 10x, honest, release binary
//! from `7332b562`) built its whole first plan except the cone of
//! `take 1 copper-plate from the cell` (failed with `removed 0`): both
//! `assembling-machine-1` placements, their recipes, the charges, one pole
//! and `research automation`. Everything else stood at the replan, tick
//! 53,546 -- the science cell's three chests, its four inserters, four
//! poles, the lab, and the WHOLE supply link, load arm at the kept east exit
//! `[30.5,-46.5]`, 25 belts, unload arm at `[31.5,-31.5]`. The replan
//! refused:
//!
//! ```text
//! a cell already makes copper-plate at [29.5, -46.5] and nothing can carry
//! it to the supply chest at [44.5, -32.5]: from the iron-chest at
//! [29.5, -46.5]: no belt route, blocked by 4 tile(s): [28.5, -46.5]
//! [29.5, -47.5] [29.5, -45.5] [30.5, -46.5]; ...
//! ```
//!
//! `[44.5, -32.5]` is not the standing supply chest. `assemble::complete_cell`
//! recovered a cell only around a standing MACHINE, and the machines are the
//! last parts of a cell to stand (both need `automation`, every arm needs a
//! circuit off the same take), so the half-built cell was invisible, a fresh
//! one was sited beside it, and the fresh one's supply chest needed a second
//! link out of a plate chest whose fourth side the first link's own arm
//! holds. Fixed by recovering a cell from any two of its parts on their
//! tiles; the standing link is then found by `already_filled_by_machine`.
//!
//! The second shape is the harness's: `plan --replan 1 --fail "copper-plate
//! from the cell"` abandons every INSERTER of the link (each needs a circuit)
//! and leaves every belt. `connect::standing_run` finishes such a run with
//! its two arms rather than routing round its belts; asserted here on this
//! world with the link's arms taken out.
//!
//! The fixture is what the tool writes, and is regenerated by it:
//!
//! ```text
//! factorio-bot plan --world workspace/scripts/map.json \
//!     --standing-from-run workspace/runs/run-1788941729-70024 --at-tick 53546 \
//!     --all --goal sustain:copper-plate:15:36000 \
//!     --goal producing:automation-science-pack:6 \
//!     --save-standing crates/planner/tests/fixtures/run-1788941729-70024-tick53546.json
//! ```
//!
//! Like `replan_on_standing_world`, it FAILS rather than skips when
//! `workspace/scripts/map.json` is absent, unless `CI` is set.

use factorio_bot_core::factorio::world::FactorioSurface;
use factorio_bot_core::record::standing::StandingSnapshot;
use factorio_bot_core::types::Position;
use factorio_bot_planner::standing::world_with;
use factorio_bot_planner::{
    ActionKind, ActionNetwork, BotId, Goal, PlanState, expand, pick_chain_actor, registry_for,
};
use std::path::PathBuf;
use std::sync::Arc;

/// The seed-31337 t=0 dump, or a loud failure saying how to get it.
fn dump() -> Option<Arc<FactorioSurface>> {
    let path: PathBuf =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../workspace/scripts/map.json");
    let Ok(path) = path.canonicalize() else {
        let message = format!(
            "workspace/scripts/map.json is not present at {}, so the replan against run \
             70024's world did NOT run. In a worktree: `ln -s <main checkout>/workspace/\
             scripts/map.json <worktree>/workspace/scripts/map.json`.",
            path.display()
        );
        if std::env::var_os("CI").is_some() {
            eprintln!("SKIPPED under CI: {message}");
            return None;
        }
        panic!("{message}");
    };
    let raw = std::fs::read_to_string(&path).expect("the dump is readable");
    Some(Arc::new(
        factorio_bot_core::serde_json::from_str(&raw).expect("map.json is a world dump"),
    ))
}

/// The run's record at the tick it replanned and refused.
fn fixture() -> StandingSnapshot {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/run-1788941729-70024-tick53546.json");
    StandingSnapshot::read_from(&path).expect("the fixture is in the tree and parses")
}

/// The link's two arms, as the record places them: the load arm on the
/// plate chest's kept east exit and the unload arm south of the supply chest.
const LOAD_ARM: (f64, f64) = (30.5, -46.5);
const UNLOAD_ARM: (f64, f64) = (31.5, -31.5);

fn standing_world(snapshot: StandingSnapshot) -> Option<(PlanState, Vec<BotId>)> {
    let base = dump()?;
    let (world, standing) = world_with(&base, &snapshot);
    assert_eq!(
        standing.placed,
        snapshot.entities.len(),
        "every entity of the keyframe stands, or this is a test of a different world: {standing:?}"
    );
    let bots: Vec<BotId> = snapshot.bots.iter().map(|b| BotId(b.id)).collect();
    Some((PlanState::from_world(world, &bots), bots))
}

/// The run's goal, as `scripts/continuous_supply.lua` states it.
fn goal() -> Goal {
    Goal::All(vec![
        Goal::Sustain {
            item: "copper-plate".into(),
            per_minute: 15,
            window_ticks: 36_000,
        },
        Goal::Producing {
            item: "automation-science-pack".into(),
            per_minute: 6,
        },
    ])
}

fn placed(net: &ActionNetwork, name: &str) -> Vec<Position> {
    let mut out: Vec<Position> = net
        .actions()
        .filter_map(|a| match &a.kind {
            ActionKind::Place { entity } if entity.name == name => Some(entity.position.clone()),
            _ => None,
        })
        .collect();
    out.sort_by(|a, b| a.x.total_cmp(&b.x).then(a.y.total_cmp(&b.y)));
    out
}

fn replan(state: &PlanState, bots: &[BotId]) -> ActionNetwork {
    let chain_actor = pick_chain_actor(state, bots).expect("the roster has a chain actor");
    expand(&[goal()], state, &registry_for(bots), chain_actor)
        .unwrap_or_else(|refusal| panic!("the replan of run 70024 refused: {refusal}"))
}

/// The replan finishes the standing cell -- the two machines go exactly
/// where plan 1 meant them, no chest and no belt is placed, and the link
/// that stands is left alone.
#[test]
fn the_replan_of_run_1788941729_70024_finishes_its_half_built_cell() {
    let Some((state, bots)) = standing_world(fixture()) else {
        return;
    };
    let net = replan(&state, &bots);
    assert_eq!(
        placed(&net, "assembling-machine-1"),
        vec![Position::new(31.5, -27.5), Position::new(35.5, -27.5)],
        "the machines go where plan 1 meant them: the cell is finished, not re-sited"
    );
    assert_eq!(
        placed(&net, "iron-chest"),
        Vec::<Position>::new(),
        "every chest of the cell stands"
    );
    assert_eq!(
        placed(&net, "transport-belt"),
        Vec::<Position>::new(),
        "the supply link stands whole; no second link"
    );
    assert_eq!(
        placed(&net, "inserter"),
        Vec::<Position>::new(),
        "every arm of the cell and of the link stands"
    );
}

/// The harness's shape on the same world: the link's arms abandoned, its
/// belts standing. The replan places exactly the two arms back on their
/// tiles and lays no belt.
#[test]
fn a_link_missing_only_its_arms_is_finished_with_two_arms() {
    let mut snapshot = fixture();
    let before = snapshot.entities.len();
    snapshot.entities.retain(|e| {
        !(e.name == "inserter"
            && [LOAD_ARM, UNLOAD_ARM]
                .iter()
                .any(|(x, y)| e.position.x() == *x && e.position.y() == *y))
    });
    assert_eq!(
        before - snapshot.entities.len(),
        2,
        "the two link arms are taken out"
    );
    let Some((state, bots)) = standing_world(snapshot) else {
        return;
    };
    let net = replan(&state, &bots);
    assert_eq!(
        placed(&net, "transport-belt"),
        Vec::<Position>::new(),
        "the belts stand; none is laid again and no second run is routed"
    );
    assert_eq!(
        placed(&net, "inserter"),
        vec![
            Position::new(LOAD_ARM.0, LOAD_ARM.1),
            Position::new(UNLOAD_ARM.0, UNLOAD_ARM.1)
        ],
        "exactly the two arms of the standing link, on their own tiles"
    );
    assert_eq!(
        placed(&net, "assembling-machine-1"),
        vec![Position::new(31.5, -27.5), Position::new(35.5, -27.5)],
        "and the cell is still the one plan 1 began"
    );
}
