//! A replan against the world `run-1788936524-99544` left standing.
//!
//! The run (seed 31337, four headless bots at 10x, honest, release binary
//! from `c1fd2620`) built its whole first plan except the abandoned cone of
//! `take 10 copper-plate from the cell`, and the supervisor's replan at tick
//! 62,222 refused with
//!
//! ```text
//! a cell already makes copper-plate at [29.5, -46.5] and nothing can carry
//! it to the supply chest at [42.5, -26.5]: from the iron-chest at
//! [29.5, -46.5]: the obstacle needs an underground span of 7 tiles and the
//! belt allows 5; ...
//! ```
//!
//! which three notes read as the plate cell's own coal runs sealing its
//! exit. Reproduced here from the run's own keyframe, it was neither: the
//! plate chest's kept exit tunnels out north with a 2-span pair, and what
//! could not be reached was the SINK. `assemble::plan_cell` had sited the
//! replacement science cell on the shore beside the standing plant, and its
//! supply chest's only free side was the one-tile gap between the steam
//! engine and the boiler -- a belt tile whose every neighbour but the arm's
//! own is engine, boiler or pipe. `route.rs` then measured "span of 7" off
//! the straight line from the source, which says nothing about which end is
//! shut.
//!
//! Two things fixed, each asserted below: a cell is sited only where a belt
//! can be laid into its supply chest from open ground (`assemble::
//! supply_chest_is_reachable`, the same question `sustain::choose_exit` asks
//! of a plate chest's exit), and a destination with nothing free beside it
//! is refused by its four walls, never by a span (`route::walls_around`).
//!
//! The fixture is what the tool writes, and is regenerated by it:
//!
//! ```text
//! factorio-bot plan --world workspace/scripts/map.json \
//!     --standing-from-run workspace/runs/run-1788936524-99544 --at-tick 62222 \
//!     --all --goal sustain:copper-plate:15:36000 \
//!     --goal producing:automation-science-pack:6 \
//!     --save-standing crates/planner/tests/fixtures/run-1788936524-99544-tick62222.json
//! ```
//!
//! Like `replan_on_standing_world`, it FAILS rather than skips when
//! `workspace/scripts/map.json` is absent, unless `CI` is set.

use factorio_bot_core::factorio::world::FactorioSurface;
use factorio_bot_core::record::standing::StandingSnapshot;
use factorio_bot_core::types::Position;
use factorio_bot_planner::method::connect::connect_steps_reserving;
use factorio_bot_planner::standing::world_with;
use factorio_bot_planner::{
    ActionKind, BotId, ExpansionCtx, Goal, PlanState, expand, pick_chain_actor, registry_for,
};
use std::path::PathBuf;
use std::sync::Arc;

/// The seed-31337 t=0 dump, or a loud failure saying how to get it.
fn dump() -> Option<Arc<FactorioSurface>> {
    let path: PathBuf =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../workspace/scripts/map.json");
    let Ok(path) = path.canonicalize() else {
        let message = format!(
            "workspace/scripts/map.json is not present at {}, so the replan against run \
             99544's world did NOT run. In a worktree: `ln -s <main checkout>/workspace/\
             scripts/map.json <worktree>/workspace/scripts/map.json`.",
            path.display()
        );
        if std::env::var_os("CI").is_some() {
            eprintln!("SKIPPED under CI: {message}");
            return None;
        }
        panic!("{message}");
    };
    let raw = std::fs::read_to_string(&path).expect("the dump is readable");
    Some(Arc::new(
        factorio_bot_core::serde_json::from_str(&raw).expect("map.json is a world dump"),
    ))
}

/// The run's record at the tick it replanned and refused.
fn fixture() -> StandingSnapshot {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/run-1788936524-99544-tick62222.json");
    StandingSnapshot::read_from(&path).expect("the fixture is in the tree and parses")
}

fn standing_world() -> Option<(PlanState, Vec<BotId>)> {
    let base = dump()?;
    let fixture = fixture();
    let (world, standing) = world_with(&base, &fixture);
    assert_eq!(
        standing.placed,
        fixture.entities.len(),
        "every entity of the keyframe stands, or this is a test of a different world: {standing:?}"
    );
    let bots: Vec<BotId> = fixture.bots.iter().map(|b| BotId(b.id)).collect();
    Some((PlanState::from_world(world, &bots), bots))
}

/// The run's goal, as `scripts/continuous_supply.lua` states it.
fn goal() -> Goal {
    Goal::All(vec![
        Goal::Sustain {
            item: "copper-plate".into(),
            per_minute: 15,
            window_ticks: 36_000,
        },
        Goal::Producing {
            item: "automation-science-pack".into(),
            per_minute: 6,
        },
    ])
}

/// The plate cell's exit is NOT sealed by its ring: asked of `connect`
/// directly, with a bare chest where the run's replan had put its supply
/// chest and nothing else of that cell, the link out of the plate chest
/// routes -- tunnelling north over the first plan's own link belt. So the
/// wall the refusal blamed was never on the source's side.
#[test]
fn the_plate_chest_of_run_1788936524_99544_has_a_way_out() {
    let Some((state, bots)) = standing_world() else {
        return;
    };
    let chain_actor = pick_chain_actor(&state, &bots).expect("the roster has a chain actor");
    let plate_chest = state
        .entity_at(&Position::new(29.5, -46.5))
        .expect("the plate chest stands");
    let mut ctx = ExpansionCtx::new(state.fork(), chain_actor);
    let sink = Position::new(42.5, -26.5);
    let area = ctx
        .state
        .collision_area_facing(
            "iron-chest",
            &sink,
            factorio_bot_core::types::Direction::North,
        )
        .expect("a chest has a box");
    let chest = factorio_bot_core::types::FactorioEntity {
        name: "iron-chest".into(),
        entity_type: "container".into(),
        position: sink,
        direction: 0,
        bounding_box: area,
        ..Default::default()
    };
    ctx.state.create_entity(chest.clone());
    let steps = connect_steps_reserving(
        &mut ctx,
        &plate_chest,
        &chest,
        &"copper-plate".into(),
        "burner-inserter",
        &[],
    )
    .unwrap_or_else(|refusal| panic!("the plate chest is sealed after all: {refusal}"));
    // A belt run is one bot's job, so its placements sit inside a
    // `Step::Owned`; walk into it rather than reading the top level only.
    fn places(steps: &[factorio_bot_planner::Step], out: &mut Vec<String>) {
        for step in steps {
            match step {
                factorio_bot_planner::Step::Act(action) => {
                    if let ActionKind::Place { entity } = &action.kind {
                        out.push(format!("{} at {}", entity.name, entity.position));
                    }
                }
                factorio_bot_planner::Step::Owned { steps, .. } => places(steps, out),
                _ => {}
            }
        }
    }
    let mut placed = Vec::new();
    places(&steps, &mut placed);
    assert!(
        placed.iter().any(|p| p.starts_with("underground-belt")),
        "the pocket round the kept exit is sealed on the surface, so the link tunnels out: \
         {placed:#?}"
    );
    assert!(
        placed
            .iter()
            .any(|p| p == "burner-inserter at [30.5, -46.5]"),
        "the link leaves by the kept east exit: {placed:#?}"
    );
}

/// The whole replan plans. Before `supply_chest_is_reachable` the science
/// cell was sited with its supply chest in the engine/boiler gap and the
/// bundle refused on the link to it; now the cell is sited where a belt can
/// reach its chest, and the link is laid -- with the pair, and the
/// `logistics` the pair needs, in the plan.
#[test]
fn the_replan_of_run_1788936524_99544_plans() {
    let Some((state, bots)) = standing_world() else {
        return;
    };
    let chain_actor = pick_chain_actor(&state, &bots).expect("the roster has a chain actor");
    let net = expand(&[goal()], &state, &registry_for(&bots), chain_actor)
        .unwrap_or_else(|err| panic!("the replan refuses again: {err}"));
    let placed = |name: &str| -> Vec<Position> {
        net.actions()
            .filter_map(|action| match &action.kind {
                ActionKind::Place { entity } if entity.name == name => {
                    Some(entity.position.clone())
                }
                _ => None,
            })
            .collect()
    };
    assert!(
        !placed("assembling-machine-1").is_empty(),
        "the replan places a science cell, or it measures nothing"
    );
    assert!(
        !placed("iron-chest")
            .iter()
            .any(|chest| (chest.x() - 42.5).abs() < 0.1 && (chest.y() + 26.5).abs() < 0.1),
        "a chest is back in the engine/boiler gap at [42.5, -26.5]"
    );
    assert!(
        !placed("underground-belt").is_empty(),
        "the link out of the plate chest crosses the first plan's own belt with a pair"
    );
}
