[package]
name = "factorio-bot-scripting"
version = "0.2.16"
authors = ["Artur Hallmann <arturh@arturh.de>"]
edition = "2021"

[package.metadata.release]
tag = false
push = false
publish = false

[dependencies]
factorio-bot-core = { path = "../core" }
gag = "^1.0"
